openapi: 3.0.0
info:
  title: Logistics Service API
  description: API documentation for the logistics service
  version: 1.0.0
servers:
  - url: 'http://localhost:3001' 
paths:
  /shipments/create:
    post:
      summary: Create a new shipment
      description: Create a new shipment with sender, receiver, and shipment details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender:
                  type: string
                  example: "John Doe"
                receiver:
                  type: string
                  example: "Jane Doe"
                details:
                  type: string
                  example: "Package of electronics"
              required:
                - sender
                - receiver
                - details
      responses:
        201:
          description: Shipment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Shipment created successfully."
                  shipment:
                    type: object
                    properties:
                      trackingNumber:
                        type: string
                        example: "TRK-1632948400000"
                      sender:
                        type: string
                        example: "John Doe"
                      receiver:
                        type: string
                        example: "Jane Doe"
                      details:
                        type: string
                        example: "Package of electronics"
        400:
          description: Missing required fields
        500:
          description: Internal server error

  /shipments/update/{id}:
    put:
      summary: Update shipment status
      description: Update the status of an existing shipment by providing shipment ID and status.
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the shipment
          schema:
            type: string
            example: "60b8d8b2f0f0f6d5a1b2a0b9"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "Delivered"
              required:
                - status
      responses:
        200:
          description: Shipment status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Shipment status updated."
                  shipment:
                    type: object
                    properties:
                      trackingNumber:
                        type: string
                        example: "TRK-1632948400000"
                      sender:
                        type: string
                        example: "John Doe"
                      receiver:
                        type: string
                        example: "Jane Doe"
                      status:
                        type: string
                        example: "Delivered"
        400:
          description: Invalid request
        404:
          description: Shipment not found
        500:
          description: Internal server error

  /shipments/track/{trackingNumber}:
    get:
      summary: Track a shipment by tracking number
      description: Retrieve shipment details based on the tracking number.
      parameters:
        - in: path
          name: trackingNumber
          required: true
          description: The tracking number of the shipment
          schema:
            type: string
            example: "TRK-1632948400000"
      responses:
        200:
          description: Shipment details found
          content:
            application/json:
              schema:
                type: object
                properties:
                  trackingNumber:
                    type: string
                    example: "TRK-1632948400000"
                  sender:
                    type: string
                    example: "John Doe"
                  receiver:
                    type: string
                    example: "Jane Doe"
                  details:
                    type: string
                    example: "Package of electronics"
                  status:
                    type: string
                    example: "In Transit"
        404:
          description: Shipment not found
        500:
          description: Internal server error

  /shipments/user:
    get:
      summary: Get all shipments by user
      description: Retrieve all shipments associated with the authenticated user.
      responses:
        200:
          description: Shipments retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    trackingNumber:
                      type: string
                      example: "TRK-1632948400000"
                    sender:
                      type: string
                      example: "John Doe"
                    receiver:
                      type: string
                      example: "Jane Doe"
                    details:
                      type: string
                      example: "Package of electronics"
                    status:
                      type: string
                      example: "In Transit"
        500:
          description: Internal server error
